export const cyan: { [key: string]: string } = {
	'--primary-light': '#06b6d4',
	'--primary-main': '#0891b2',
	'--primary-dark': '#0e7490',
	'--primary-contrast-light': '#f9fafb',
	'--primary-contrast-main': '#f3f4f6',
	'--primary-contrast-dark': '#e5e7eb',
	'--secondary-light': '#a5f3fc',
	'--secondary-main': '#67e8f9',
	'--secondary-dark': '#22d3ee',
	'--secondary-contrast-light': '#0e7490',
	'--secondary-contrast-main': '#155e75',
	'--secondary-contrast-dark': '#164e63',
	'--tertiary-light': '#e5e7eb',
	'--tertiary-main': '#d1d5db',
	'--tertiary-dark': '#9ca3af',
	'--tertiary-contrast-light': '#1f2937',
	'--tertiary-contrast-main': '#111827',
	'--tertiary-contrast-dark': '#030712',
	'--badge-main': '#dc2626',
	'--badge-contrast': '#f8fafc'
};
