export const indigo: { [key: string]: string } = {
	'--primary-light': '#6366f1',
	'--primary-main': '#4f46e5',
	'--primary-dark': '#4338ca',
	'--primary-contrast-light': '#f9fafb',
	'--primary-contrast-main': '#f3f4f6',
	'--primary-contrast-dark': '#e5e7eb',
	'--secondary-light': '#c7d2fe',
	'--secondary-main': '#a5b4fc',
	'--secondary-dark': '#818cf8',
	'--secondary-contrast-light': '#4338ca',
	'--secondary-contrast-main': '#3730a3',
	'--secondary-contrast-dark': '#312e81',
	'--tertiary-light': '#e5e7eb',
	'--tertiary-main': '#d1d5db',
	'--tertiary-dark': '#9ca3af',
	'--tertiary-contrast-light': '#1f2937',
	'--tertiary-contrast-main': '#111827',
	'--tertiary-contrast-dark': '#030712',
	'--badge-main': '#dc2626',
	'--badge-contrast': '#f8fafc'
};
