export const pink: { [key: string]: string } = {
	'--primary-light': '#ec4899',
	'--primary-main': '#db2777',
	'--primary-dark': '#be185d',
	'--primary-contrast-light': '#f9fafb',
	'--primary-contrast-main': '#f3f4f6',
	'--primary-contrast-dark': '#e5e7eb',
	'--secondary-light': '#fbcfe8',
	'--secondary-main': '#f9a8d4',
	'--secondary-dark': '#f472b6',
	'--secondary-contrast-light': '#be185d',
	'--secondary-contrast-main': '#9d174d',
	'--secondary-contrast-dark': '#831843',
	'--tertiary-light': '#e5e7eb',
	'--tertiary-main': '#d1d5db',
	'--tertiary-dark': '#9ca3af',
	'--tertiary-contrast-light': '#1f2937',
	'--tertiary-contrast-main': '#111827',
	'--tertiary-contrast-dark': '#030712',
	'--badge-main': '#020617',
	'--badge-contrast': '#fafaf9'
};
