export const purple: { [key: string]: string } = {
	'--primary-light': '#a855f7',
	'--primary-main': '#9333ea',
	'--primary-dark': '#7e22ce',
	'--primary-contrast-light': '#f9fafb',
	'--primary-contrast-main': '#f3f4f6',
	'--primary-contrast-dark': '#e5e7eb',
	'--secondary-light': '#e9d5ff',
	'--secondary-main': '#d8b4fe',
	'--secondary-dark': '#c084fc',
	'--secondary-contrast-light': '#7e22ce',
	'--secondary-contrast-main': '#6b21a8',
	'--secondary-contrast-dark': '#581c87',
	'--tertiary-light': '#e5e7eb',
	'--tertiary-main': '#d1d5db',
	'--tertiary-dark': '#9ca3af',
	'--tertiary-contrast-light': '#1f2937',
	'--tertiary-contrast-main': '#111827',
	'--tertiary-contrast-dark': '#030712',
	'--badge-main': '#dc2626',
	'--badge-contrast': '#f8fafc'
};
