export const red: { [key: string]: string } = {
	'--primary-light': '#ef4444',
	'--primary-main': '#dc2626',
	'--primary-dark': '#b91c1c',
	'--primary-contrast-light': '#f9fafb',
	'--primary-contrast-main': '#f3f4f6',
	'--primary-contrast-dark': '#e5e7eb',
	'--secondary-light': '#fecaca',
	'--secondary-main': '#fca5a5',
	'--secondary-dark': '#f87171',
	'--secondary-contrast-light': '#b91c1c',
	'--secondary-contrast-main': '#991b1b',
	'--secondary-contrast-dark': '#7f1d1d',
	'--tertiary-light': '#e5e7eb',
	'--tertiary-main': '#d1d5db',
	'--tertiary-dark': '#9ca3af',
	'--tertiary-contrast-light': '#1f2937',
	'--tertiary-contrast-main': '#111827',
	'--tertiary-contrast-dark': '#030712',
	'--badge-main': '#020617',
	'--badge-contrast': '#fafaf9'
};
