export const rose: { [key: string]: string } = {
	'--primary-light': '#f43f5e',
	'--primary-main': '#e11d48',
	'--primary-dark': '#be123c',
	'--primary-contrast-light': '#f9fafb',
	'--primary-contrast-main': '#f3f4f6',
	'--primary-contrast-dark': '#e5e7eb',
	'--secondary-light': '#fecdd3',
	'--secondary-main': '#fda4af',
	'--secondary-dark': '#fb7185',
	'--secondary-contrast-light': '#be123c',
	'--secondary-contrast-main': '#9f1239',
	'--secondary-contrast-dark': '#881337',
	'--tertiary-light': '#e5e7eb',
	'--tertiary-main': '#d1d5db',
	'--tertiary-dark': '#9ca3af',
	'--tertiary-contrast-light': '#1f2937',
	'--tertiary-contrast-main': '#111827',
	'--tertiary-contrast-dark': '#030712',
	'--badge-main': '#020617',
	'--badge-contrast': '#fafaf9'
};
