export const sky: { [key: string]: string } = {
	'--primary-light': '#0ea5e9',
	'--primary-main': '#0284c7',
	'--primary-dark': '#0369a1',
	'--primary-contrast-light': '#f9fafb',
	'--primary-contrast-main': '#f3f4f6',
	'--primary-contrast-dark': '#e5e7eb',
	'--secondary-light': '#bae6fd',
	'--secondary-main': '#7dd3fc',
	'--secondary-dark': '#38bdf8',
	'--secondary-contrast-light': '#0369a1',
	'--secondary-contrast-main': '#075985',
	'--secondary-contrast-dark': '#0c4a6e',
	'--tertiary-light': '#e5e7eb',
	'--tertiary-main': '#d1d5db',
	'--tertiary-dark': '#9ca3af',
	'--tertiary-contrast-light': '#1f2937',
	'--tertiary-contrast-main': '#111827',
	'--tertiary-contrast-dark': '#030712',
	'--badge-main': '#dc2626',
	'--badge-contrast': '#f8fafc'
};
