export const teal: { [key: string]: string } = {
	'--primary-light': '#14b8a6',
	'--primary-main': '#0d9488',
	'--primary-dark': '#0f766e',
	'--primary-contrast-light': '#f9fafb',
	'--primary-contrast-main': '#f3f4f6',
	'--primary-contrast-dark': '#e5e7eb',
	'--secondary-light': '#99f6e4',
	'--secondary-main': '#5eead4',
	'--secondary-dark': '#2dd4bf',
	'--secondary-contrast-light': '#0f766e',
	'--secondary-contrast-main': '#115e59',
	'--secondary-contrast-dark': '#134e4a',
	'--tertiary-light': '#e5e7eb',
	'--tertiary-main': '#d1d5db',
	'--tertiary-dark': '#9ca3af',
	'--tertiary-contrast-light': '#1f2937',
	'--tertiary-contrast-main': '#111827',
	'--tertiary-contrast-dark': '#030712',
	'--badge-main': '#dc2626',
	'--badge-contrast': '#f8fafc'
};
