export const yellow: { [key: string]: string } = {
	'--primary-light': '#eab308',
	'--primary-main': '#ca8a04',
	'--primary-dark': '#a16207',
	'--primary-contrast-light': '#f9fafb',
	'--primary-contrast-main': '#f3f4f6',
	'--primary-contrast-dark': '#e5e7eb',
	'--secondary-light': '#fef08a',
	'--secondary-main': '#fde047',
	'--secondary-dark': '#facc15',
	'--secondary-contrast-light': '#a16207',
	'--secondary-contrast-main': '#854d0e',
	'--secondary-contrast-dark': '#713f12',
	'--tertiary-light': '#e5e7eb',
	'--tertiary-main': '#d1d5db',
	'--tertiary-dark': '#9ca3af',
	'--tertiary-contrast-light': '#1f2937',
	'--tertiary-contrast-main': '#111827',
	'--tertiary-contrast-dark': '#030712',
	'--badge-main': '#020617',
	'--badge-contrast': '#fafaf9'
};
